### ISSUE TITLE
packaging a build as an extension?

### ISSUE THREAD

**Issue by boredsquirrel** [Bali10050/Darkly#10]
Hey,

while compiling in a distrobox, I had issues getting it to my host system.

The distrobox is an isolated environment, at least against accidental garbage config files. So I use a variable to have a different home inside the box than on the host.

Do you know if this theme can be packaged as a KDE Theme package, so it can be added to store.kde.org and installed from a file?

**Comment by Bali10050** [comment]
I don't think that it can be packaged as a kde theme, or atleast I have never seen any qt themes that can be.

**Comment by TKK13909** [comment]
The Distrobox method should install to `~/.local/lib64/plugins/styles/` so you should be able to copy `lightly6.so` from wherever that is in your Distrobox config to the proper directory and then set the environment variable (`export QT_PLUGIN_PATH=$HOME/.local/lib64/plugins:$QT_PLUGIN_PATH`).

Disclaimer: _I am still testing the distrobox method so some things might be different for your system. Feedback is much appreciated._

**Comment by boredsquirrel** [comment]
thanks for your reply!

To make this easier, instead of "make install" we could just copy the files over?

Distrobox can use a variable to use a custom separated homedir per box, which makes a ton of sense to actually have independend environments, where dotfiles cannot break another.

---

I already successfully compiled the theme and placed all the files in that directory.

The thing is, on Fedora Kinoite 40, there is no .local/lib64

there is .local/lib though

I placed all the files in there:

```
~/.local/lib64 ❯❯❯ tree plugins                                                                                                                                                     master ◼
plugins
├── kstyle_config
│   └── lightlystyleconfig.so
├── liblightlycommon6.so -> liblightlycommon6.so.6
├── liblightlycommon6.so.6 -> liblightlycommon6.so.6.80
├── liblightlycommon6.so.6.80
├── lightly6.so
├── lightly-settings6
├── org.kde.kdecoration2.kcm
│   └── kcm_lightlydecoration.so
└── org.kde.lightly.so
```

but they dont show up under "Plasma themes"

Anything you see that could be a problem here?

**Comment by TKK13909** [comment]
There is no Plasma theme associated with this project yet. Lightly is an _application_ style so you need to go into `Colors & Themes > Application Style` and select `Lightly`. Plasma comes with 3 default themes so if you see `Breeze`, `Fusion`, and `MS Windows 9x` but no `Lightly` then it installed improperly.

I also just submitted a new PR to make the install work better: https://github.com/Bali10050/Lightly/pull/15

**Comment by TKK13909** [comment]
> Distrobox can use a variable to use a custom separated homedir per box, which makes a ton of sense to actually have independend environments, where dotfiles cannot break another.

I actually didn't know about this feature but it makes sense. Thanks for informing me!

**Comment by TKK13909** [comment]
Should probably close this issue at some point but I would like to mention that there is a version of Lightly listed on the store so we probably could get this one listed there without too much trouble. https://store.kde.org/p/1414190

Just something to think about in the future.

**Comment by Bali10050** [comment]
Now that the project has been renamed, I listed it on the kde store:

<https://store.kde.org/p/2233462/>

It should have the packages of the latest release, and the source code from 5de7c8b for the updated readme
