### ISSUE TITLE
NixOS Not Showing Lightly Theme? 

### ISSUE THREAD

**Issue by AyushmanOfficial** [Bali10050/Darkly#64]
I followed the steps in the `Readme.md` and added the url to my `flake.nix` then i added the configuration in `home.nix` after that i ran `sudo nixos-rebuild switch` and rebooted my system and i should've see Lightly in `qt5ct` But i don't is there any extra configuration or steps or did i just miss anything?

System Details:
NixOS 24.11.20241205.4dc2fc4 (Vicuna) x86_64
Hyprland (Wayland)

Screenshots:
![20241214_02h36m44s_grim](https://github.com/user-attachments/assets/9cbd8b68-950f-40a2-aeab-29746f12efa2)

**Comment by Bali10050** [comment]
@zspher can you please help with this?

**Comment by zspher** [comment]
hi,
is lightly available in the styles list?
is lightly present in `~/.local/state/nix/profile/lib/qt-5.15.15/plugins/styles`?

**Comment by AyushmanOfficial** [comment]
> hi, is lightly available in the styles list? is lightly present in `~/.local/state/nix/profile/lib/qt-5.15.15/plugins/styles`?

Let me check it out actually i removed it i'll edit this comment and let you know wait!

**Comment by zspher** [comment]
i had assumed you were using `home-manager`, i seems you are using nixos w/o `home-manager`. In that case use the ff.
```nix
qt.platformTheme = "qt5ct";
environment.systemPackages = with pkgs; [
  inputs.lightly.packages.${pkgs.system}.lightly-qt5
  inputs.lightly.packages.${pkgs.system}.lightly-qt6
]
```

**Comment by AyushmanOfficial** [comment]
> i had assumed you were using `home-manager`, i seems you are using nixos w/o `home-manager`. In that case use the ff.
> 
> ```nix
> qt.platformTheme = "qt5ct";
> environment.systemPackages = with pkgs; [
>   inputs.lightly.packages.${pkgs.system}.lightly-qt5
>   inputs.lightly.packages.${pkgs.system}.lightly-qt6
> ]
> ```
> 
> after you have done so. see if `/run/current-system/sw/lib/qt-5.15.15/plugins/styles` has lightly ps. if you use the above, you dont need to install `libsForQt5.qt5ct` via `environment.systemPackages` as that is what `qt.platformTheme` does

Ok great! I'll try that mate! btw did you miss a ";"
